FROM almondsh/almond:latest

USER root

RUN apt-get update & \
    apt-get install openjdk-8-jre-headless & \
    rm -rf /tmp/* /var/tmp/*

USER $NB_UID

COPY binder/postBuild /postBuild
RUN /postBuild

